version: '3'
services:
    minecraft-server:
        container_name: mc
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        tty: true
        stdin_open: true
        restart: always
        volumes:
            - ./data:/data
        environment:
            - EULA="TRUE"
            - VERSION=1.14.3
            - SERVER_NAME="My Minecraft Server"
            - REPLACE_ENV_VARIABLES="TRUE"
            - DIFFICULTY=normal  # peaceful, easy, normal, hard
            - ENABLE_COMMAND_BLOCK=true
            - FORCE_GAMEMODE=false
